require 'httparty'
require 'cgi'
require 'pp' # debug only

require 'clashinator/base.rb'
require 'clashinator/array_resource.rb'
require 'clashinator/army.rb'
require 'clashinator/season.rb'
require 'clashinator/clan_ranking.rb'
require 'clashinator/player_ranking.rb'
require 'clashinator/achievement.rb'
require 'clashinator/troop.rb'
require 'clashinator/hero.rb'
require 'clashinator/spell.rb'
require 'clashinator/warlog.rb'
require 'clashinator/badge_url.rb'
require 'clashinator/league.rb'
require 'clashinator/location.rb'
require 'clashinator/player.rb'
require 'clashinator/clan.rb'
require 'clashinator/version.rb'
